name: twigrass

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: "0 0,6,12,18 * * *"
env:
  cache-version: v2

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Check is running
        uses: actions/github-script@v4
        id: runningCount
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const runed = await github.actions.listWorkflowRuns({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: "twigrass.yml",
              status:"in_progress"
            });
            return runed.data.total_count
          result-encoding: string
      - uses: actions/checkout@v2
        if: steps.runningCount.outputs.result=='1'
      - name: Get current date
        if: steps.runningCount.outputs.result=='1'
        id: date
        run: echo "set-output name=date::$(date '+%Y%m%d-%H%M%S')"
      - uses: actions/cache@v2
        if: steps.runningCount.outputs.result=='1'
        with:
          path: ./dates_cache.txt
          key: ${{ runner.os }}-twigrass-${{ env.cache-version }}-${{ steps.date.outputs.date }}
          restore-keys: |
            ${{ runner.os }}-twigrass-${{ env.cache-version }}-
      - name: generate
        if: steps.runningCount.outputs.result=='1'
        run: ./twigrass.sh
        env:
          TWITTER_USER_NAME: ${{ secrets.TWITTER_USER_NAME }}
          PIXELA_USER_NAME: ${{ secrets.PIXELA_USER_NAME }}
          PIXELA_GRAPH_ID: ${{ secrets.PIXELA_GRAPH_ID }}
          PIXELA_USER_TOKEN: ${{ secrets.PIXELA_USER_TOKEN }}
